@startuml
[*] --> Администратор
Администратор --> DevOps_инженер
Администратор --> Специалист_техподдержки
Администратор --> Менеджер_магазина
Менеджер_магазина --> Оператор
DevOps_инженер --> Специалист_техподдержки : поддержка
@enduml
