@startuml
package "Мониторинг системы" {
  [Мониторинг Cron-задач]
  [Мониторинг RabbitMQ]
  [Мониторинг Daemon процессов]
  [Мониторинг Индексов]
  [Мониторинг Кэширования]
}

package "Основные процессы Magento" {
  [Обработка заказов]
  [Управление товарами]
  [Обработка платежных транзакций]
  [Управление промо-акциями]
  [Управление стоками для товаров]
  [Импорт/экспорт данных]
}

package "Фоновые процессы Magento" {
  [Выполнение Cron-задач]
  [Обработка очередей]
  [Индексация данных]
  [Обновление кэша]
  [Синхронизация данных]
  [Генерация отчетов]
}

package "Система уведомлений" {
  [Обработка ошибок]
  [Отправка в Telegram]
  [Отправка на Email]
  [Журналирование]
  [Эскалация проблем]
}

[Мониторинг системы] --> [Фоновые процессы Magento] : отслеживает
[Мониторинг системы] --> [Система уведомлений] : оповещает о проблемах
[Фоновые процессы Magento] --> [Основные процессы Magento] : поддерживает работу
[Система уведомлений] --> [Основные процессы Magento] : обеспечивает стабильность
@enduml