@startuml
title Мониторинг задач (Activity Diagram)

(*) --> "Фоновые задачи запущены"
--> "Проверка состояния задач"
--> if "Состояние: ОК?" then
      -->[да] "Фиксация успеха"
      --> (*)
    else
      -->[нет] "Отправка уведомления"
      --> (*)
    endif
@enduml 